POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkZHJlc3MyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzMwMTYwNDg1LCJ1c2VySWQiOjJ9._qUzh-pSmu2FehokBU1zUeCrhIczX2QgUXsIS9zdHo0

{
	"name":"Event 1",
	"description":"Lorem ipsum",
	"location":"Republic of Moldova",
	"dateTime":"2025-04-01T15:30:00.000Z"
}