POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkZHJlc3M1QGV4YW1wbGUuY29tIiwiZXhwIjoxNzMwMTU3NDM2LCJ1c2VySWQiOjJ9.H8UO524eELsPvmFLShVt0EYFsmI60svwv97coX22Bwc

{
	"name":"Event 1",
	"description":"Lorem ipsum",
	"location":"Republic of Moldova",
	"dateTime":"2025-04-01T15:30:00.000Z"
}