DELETE http://localhost:8080/events/6
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkZHJlc3M1QGV4YW1wbGUuY29tIiwiZXhwIjoxNzMwMTU3NDM2LCJ1c2VySWQiOjJ9.H8UO524eELsPvmFLShVt0EYFsmI60svwv97coX22Bwc
